//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Util.Var
{
    using UnityEngine;
    using Util.Var.Observe;
    
    [CreateAssetMenu(menuName = "Custom/Variable/float")]
    public sealed class FloatVariable : Variable<float>
    {
    }
    [System.Serializable()]
    public sealed class FloatReference : VariableReference<FloatVariable, ObservableFloatVariable, float>
    {
    }
}
