//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Util.Var.Events
{
    using UnityEngine;
    using Util.Var.Observe;
    
    [CreateAssetMenu(menuName = "Custom/Event/float")]
    public sealed class FloatGameEvent : GameEvent<float>
    {
    }
    [System.Serializable()]
    public sealed class FloatEventReference : EventReference<FloatGameEvent, ObservableFloatVariable, float>
    {
    }
}
